export const cities = [
  {
    city_id: '31',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Bangkalan',
    postal_code: '69118',
  },
  {
    city_id: '42',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Banyuwangi',
    postal_code: '68416',
  },
  {
    city_id: '51',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Batu',
    postal_code: '65311',
  },
  {
    city_id: '74',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Blitar',
    postal_code: '66171',
  },
  {
    city_id: '75',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Blitar',
    postal_code: '66124',
  },
  {
    city_id: '80',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Bojonegoro',
    postal_code: '62119',
  },
  {
    city_id: '86',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Bondowoso',
    postal_code: '68219',
  },
  {
    city_id: '133',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Gresik',
    postal_code: '61115',
  },
  {
    city_id: '160',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Jember',
    postal_code: '68113',
  },
  {
    city_id: '164',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Jombang',
    postal_code: '61415',
  },
  {
    city_id: '178',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Kediri',
    postal_code: '64184',
  },
  {
    city_id: '179',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Kediri',
    postal_code: '64125',
  },
  {
    city_id: '222',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Lamongan',
    postal_code: '64125',
  },
  {
    city_id: '243',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Lumajang',
    postal_code: '67319',
  },
  {
    city_id: '247',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Madiun',
    postal_code: '63153',
  },
  {
    city_id: '248',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Madiun',
    postal_code: '63122',
  },
  {
    city_id: '251',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Magetan',
    postal_code: '63314',
  },
  {
    city_id: '255',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Malang',
    postal_code: '65163',
  },
  {
    city_id: '256',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Malang',
    postal_code: '65112',
  },
  {
    city_id: '289',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Mojokerto',
    postal_code: '61382',
  },
  {
    city_id: '290',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Mojokerto',
    postal_code: '61316',
  },
  {
    city_id: '305',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Nganjuk',
    postal_code: '64414',
  },
  {
    city_id: '306',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Ngawi',
    postal_code: '63219',
  },
  {
    city_id: '317',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Pacitan',
    postal_code: '63512',
  },
  {
    city_id: '330',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Pamekasan',
    postal_code: '69319',
  },
  {
    city_id: '342',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Pasuruan',
    postal_code: '67153',
  },
  {
    city_id: '343',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Pasuruan',
    postal_code: '67118',
  },
  {
    city_id: '363',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Ponorogo',
    postal_code: '63411',
  },
  {
    city_id: '369',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Probolinggo',
    postal_code: '67282',
  },
  {
    city_id: '370',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Probolinggo',
    postal_code: '67215',
  },
  {
    city_id: '390',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Sampang',
    postal_code: '69219',
  },
  {
    city_id: '409',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Sidoarjo',
    postal_code: '61219',
  },
  {
    city_id: '418',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Situbondo',
    postal_code: '68316',
  },
  {
    city_id: '441',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Sumenep',
    postal_code: '69413',
  },
  {
    city_id: '444',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kota',
    city_name: 'Surabaya',
    postal_code: '60119',
  },
  {
    city_id: '487',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Trenggalek',
    postal_code: '66312',
  },
  {
    city_id: '489',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Tuban',
    postal_code: '62319',
  },
  {
    city_id: '492',
    province_id: 11,
    province: 'Jawa Timur',
    type: 'Kabupaten',
    city_name: 'Tulungagung',
    postal_code: '66212',
  },
  {
    city_id: '37',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Banjarnegara',
    postal_code: '53419',
  },
  {
    city_id: '41',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Banyumas',
    postal_code: '53114',
  },
  {
    city_id: '49',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Batang',
    postal_code: '51211',
  },
  {
    city_id: '76',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Blora',
    postal_code: '58219',
  },
  {
    city_id: '91',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Boyolali',
    postal_code: '57312',
  },
  {
    city_id: '92',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Brebes',
    postal_code: '52212',
  },
  {
    city_id: '105',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Cilacap',
    postal_code: '53211',
  },
  {
    city_id: '113',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Demak',
    postal_code: '59519',
  },
  {
    city_id: '134',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Grobogan',
    postal_code: '58111',
  },
  {
    city_id: '163',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Jepara',
    postal_code: '59419',
  },
  {
    city_id: '169',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Karanganyar',
    postal_code: '57718',
  },
  {
    city_id: '177',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Kebumen',
    postal_code: '54319',
  },
  {
    city_id: '181',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Kendal',
    postal_code: '51314',
  },
  {
    city_id: '196',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Klaten',
    postal_code: '57411',
  },
  {
    city_id: '209',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Kudus',
    postal_code: '59311',
  },
  {
    city_id: '249',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Magelang',
    postal_code: '56519',
  },
  {
    city_id: '250',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kota',
    city_name: 'Magelang',
    postal_code: '56133',
  },
  {
    city_id: '344',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Pati',
    postal_code: '59114',
  },
  {
    city_id: '348',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Pekalongan',
    postal_code: '51161',
  },
  {
    city_id: '349',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kota',
    city_name: 'Pekalongan',
    postal_code: '51122',
  },
  {
    city_id: '352',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Pemalang',
    postal_code: '52319',
  },
  {
    city_id: '375',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Purbalingga',
    postal_code: '53312',
  },
  {
    city_id: '377',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Purworejo',
    postal_code: '54111',
  },
  {
    city_id: '380',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Rembang',
    postal_code: '59219',
  },
  {
    city_id: '386',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kota',
    city_name: 'Salatiga',
    postal_code: '50711',
  },
  {
    city_id: '398',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Semarang',
    postal_code: '50511',
  },
  {
    city_id: '399',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kota',
    city_name: 'Semarang',
    postal_code: '50135',
  },
  {
    city_id: '427',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Sragen',
    postal_code: '57211',
  },
  {
    city_id: '433',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Sukoharjo',
    postal_code: '57514',
  },
  {
    city_id: '445',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kota',
    city_name: 'Surakarta (Solo)',
    postal_code: '57113',
  },
  {
    city_id: '472',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Tegal',
    postal_code: '52419',
  },
  {
    city_id: '473',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kota',
    city_name: 'Tegal',
    postal_code: '52114',
  },
  {
    city_id: '476',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Temanggung',
    postal_code: '56212',
  },
  {
    city_id: '497',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Wonogiri',
    postal_code: '57619',
  },
  {
    city_id: '498',
    province_id: 10,
    province: 'Jawa Tengah',
    type: 'Kabupaten',
    city_name: 'Wonosobo',
    postal_code: '56311',
  },
]
